---
title: "Final Project: Data Cleaning and Exploration"
author: "Lucy Shichman"
date: "2024-07-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# STAT 6021 Final Project: Predicting Alzheimer's Diagnosis

## Data Cleaning
### source: <https://www.kaggle.com/datasets/rabieelkharoua/alzheimers-disease-dataset?resource=download>
```{r, echo=FALSE}
library(tidyverse)
library(ggcorrplot)
```

```{r}
alz_data = read.csv("/Users/lucyshichman/Documents/MSDS/STAT6021/alzheimer-linear-regression/alzheimers_disease_data.csv")
```

Dropping column with undisclosed classified info:
```{r}
alz_data = alz_data[,-35]
```

Creating version of data w/ numerically encoding variables converted to categorical:
```{r}
alz_cat_data = alz_data %>%
  mutate(Gender = ifelse(Gender == 0,"M","F")) %>%
  mutate(Ethnicity = ifelse(Ethnicity == 0, "Caucasian",
                     ifelse(Ethnicity == 1, "African American",
                     ifelse(Ethnicity == 2, "Asian", "Other")))) %>%
  mutate(EducationLevel = ifelse(EducationLevel == 0, "None",
                          ifelse(EducationLevel == 1, "High School",
                          ifelse(EducationLevel == 2, "Bachelor's", "Higher")))) %>%
  mutate(Smoking = ifelse(Smoking == 0, "No", "Yes")) %>%
  mutate(FamilyHistoryAlzheimers = ifelse(FamilyHistoryAlzheimers == 0, "No", "Yes")) %>%
  mutate(CardiovascularDisease = ifelse(CardiovascularDisease == 0, "No", "Yes")) %>%
  mutate(Diabetes = ifelse(Diabetes == 0, "No", "Yes")) %>%
  mutate(Depression = ifelse(Depression == 0, "No", "Yes")) %>%
  mutate(HeadInjury = ifelse(HeadInjury == 0, "No", "Yes")) %>%
  mutate(Hypertension = ifelse(Hypertension == 0, "No", "Yes")) %>%
  mutate(MemoryComplaints = ifelse(MemoryComplaints == 0, "No", "Yes")) %>%
  mutate(BehavioralProblems = ifelse(BehavioralProblems == 0, "No", "Yes")) %>%
  mutate(Confusion = ifelse(Confusion == 0, "No", "Yes")) %>%
  mutate(Disorientation = ifelse(Disorientation == 0, "No", "Yes")) %>%
  mutate(PersonalityChanges = ifelse(PersonalityChanges == 0, "No", "Yes")) %>%
  mutate(DifficultyCompletingTasks = ifelse(DifficultyCompletingTasks == 0, "No", "Yes")) %>%
  mutate(Forgetfulness = ifelse(Forgetfulness == 0, "No", "Yes")) %>%
  mutate(Diagnosis = ifelse(Diagnosis == 0, "Negative", "Positive"))
  
```

## Summarizing and Visualizing
```{r}
# correlation matrix of all potential numerical predictors and response variable MMSE
alz_cat_data2 = alz_cat_data[,c('MMSE','Age','BMI','AlcoholConsumption','PhysicalActivity',
                                 'DietQuality','SleepQuality','SystolicBP','DiastolicBP',
                                 'CholesterolTotal','CholesterolLDL','CholesterolHDL',
                                 'CholesterolTriglycerides','FunctionalAssessment',
                                 'ADL')]

cor_mat = round(cor(alz_cat_data2),2)
ggcorrplot(cor_mat, lab=TRUE, lab_size=2, tl.cex = 10, method = "square")+
  scale_fill_gradient2(limits = c(-0.2, 0.2), low = "blue", mid = "white", high = "red", midpoint = 0, space = "Lab", name = "Correlation")
```
```{r}
# Scatter plots of numerical predictors vs response
long_format_data = gather(alz_cat_data, key="predictor", value ="value", 
                   Age, BMI, AlcoholConsumption, PhysicalActivity, DietQuality, SleepQuality, SystolicBP, 
                   DiastolicBP, CholesterolTotal, CholesterolLDL, CholesterolHDL, CholesterolTriglycerides,
                   FunctionalAssessment,ADL)

ggplot(long_format_data, aes(x=value, y=MMSE, color=predictor)) +
  geom_point(size=0.1)+
  facet_wrap(~predictor, scales = "free_x", ncol=4) #frees x axis to look at range of all distinct predictors
```

# Building MLR model
```{r}
# MLR model with all possible numerical predictors
model = lm(MMSE~Age+BMI+AlcoholConsumption+PhysicalActivity+DietQuality+SleepQuality+SystolicBP+
             DiastolicBP+CholesterolTotal+CholesterolLDL+CholesterolHDL+CholesterolTriglycerides+
             FunctionalAssessment+ADL, data=alz_cat_data)
summary(model)
```
```{r}
# Preform log transformations
alz_log_data = mutate(alz_cat_data, log_Age = log(Age), 
                                    log_BMI = log(BMI),
                                    log_AlcoholConsumption = log(AlcoholConsumption),
                      log_PhysicalActivity = log(PhysicalActivity),
                      log_DietQuality = log(DietQuality),
                      log_SleepQuality = log(SleepQuality),
                      log_SystolicBP = log(SystolicBP),
                      log_DiastolicBP = log(DiastolicBP),
                      log_CholesterolTotal = log(CholesterolTotal),
                      log_CholesterolLDL = log(CholesterolLDL),
                      log_CholesterolHDL = log(CholesterolHDL),
                      log_CholesterolTriglycerides = log (CholesterolTriglycerides),
                      log_FunctionalAssessment = log(FunctionalAssessment),
                      log_ADL = log(ADL),
                      log_MMSE = log(MMSE))

model_log = lm(log_MMSE~log_Age+log_BMI+log_AlcoholConsumption+log_PhysicalActivity+log_DietQuality+log_SleepQuality+log_SystolicBP+
             log_DiastolicBP+log_CholesterolTotal+log_CholesterolLDL+log_CholesterolHDL+log_CholesterolTriglycerides+
             log_FunctionalAssessment+log_ADL, data=alz_log_data)
summary(model_log)
```

```{r}
# Using AIC for variable selection
aic = stepAIC(model_log, direction='both')
summary(aic)
```
```{r}
# look at residual plot
alz_log_data2 = mutate(alz_log_data, pred=fitted(model_log), resid=residuals(model_log))
ggplot(alz_log_data2, aes(x=pred, y=resid))+
  geom_point()+
  geom_hline(yintercept =0, color="red")
```
```{r}
# QQ plot: checking normality assumption, looking at distribution of residuals
ggplot(alz_log_data2, aes(sample=resid)) +
  stat_qq() +
  stat_qq_line(color="red")
```

```{r}
# Trying lasso regularization
library(glmnet)

predictors = as.matrix(alz_cat_data[, c("Age","BMI","AlcoholConsumption","PhysicalActivity","DietQuality","SleepQuality","SystolicBP",
             "DiastolicBP","CholesterolTotal","CholesterolLDL","CholesterolHDL","CholesterolTriglycerides","FunctionalAssessment","ADL")])
response = alz_cat_data$MMSE

lasso_model = glmnet(predictors, response, family = "gaussian")
```

```{r}
# Perform cross-validation
cv_model <- cv.glmnet(predictors, response, alpha = 1, family = "gaussian")

# Best lambda value
best_lambda <- cv_model$lambda.min

# Coefficients at best lambda
best_coefficients <- coef(cv_model, s = "lambda.min")

# Plot cross-validation error curve
plot(cv_model)
```


